name: NPM & GitHub Packages

on:
  release:
    types: [created]

jobs:
  npm-registry-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@zanake'
      - run: npm clean-install
      - run: npm run build
      - run: |
          for pkg in $(find ./dist/packages/* -maxdepth 0 -type d);
            do (
              echo "Publishing : $pkg";
              cd "$pkg";
              npm publish --access public;
            );
          done
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_TOKEN}}
